// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Map: typeof import('./components/Map.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResaultWindow: typeof import('./components/ResultWindow.vue')['default']
    Resualt: typeof import('./components/ResultWindow.vue')['default']
    ResultWindow: typeof import('./components/ResultWindow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAndResult: typeof import('./components/SearchAndResult.vue')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}

export {}
